# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccp < Formula
  desc "Manage configuration profiles for Claude Code"
  homepage "https://github.com/clnt/claude-code-profiles"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clnt/claude-code-profiles/releases/download/v0.1.0/ccp_0.1.0_darwin_amd64.tar.gz"
      sha256 "5266473c60778a15a21c791338fc382df13431628871f6d0b0dfaeba1dccb9af"

      define_method(:install) do
        bin.install "ccp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clnt/claude-code-profiles/releases/download/v0.1.0/ccp_0.1.0_darwin_arm64.tar.gz"
      sha256 "57d514bbc548d67dd9f1ad7e5cb687917b48fce801fcadf189547afbcf5b7d8f"

      define_method(:install) do
        bin.install "ccp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/clnt/claude-code-profiles/releases/download/v0.1.0/ccp_0.1.0_linux_amd64.tar.gz"
      sha256 "1ebe1bbc5f1583e506ef3a55ee110e4eba687ef4ce55b4d70ba67b9eb209dc11"
      define_method(:install) do
        bin.install "ccp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clnt/claude-code-profiles/releases/download/v0.1.0/ccp_0.1.0_linux_arm64.tar.gz"
      sha256 "959cf21802739a157e74176334f04bafe4c3fe8c06004d7a21d771d11cbda676"
      define_method(:install) do
        bin.install "ccp"
      end
    end
  end
end
