# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccp < Formula
  desc "Manage configuration profiles for Claude Code"
  homepage "https://github.com/clnt/claude-code-profiles"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clnt/claude-code-profiles/releases/download/v0.1.1/ccp_0.1.1_darwin_amd64.tar.gz"
      sha256 "52140043f8feaee94668ca1974313e4ba34965229002808458d899f4371c2a6e"

      define_method(:install) do
        bin.install "ccp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clnt/claude-code-profiles/releases/download/v0.1.1/ccp_0.1.1_darwin_arm64.tar.gz"
      sha256 "d2738e6af4adea0a8a6f1b8ff13c9b7fc235fb9bf4195660ef0bcf144b8ad6a1"

      define_method(:install) do
        bin.install "ccp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/clnt/claude-code-profiles/releases/download/v0.1.1/ccp_0.1.1_linux_amd64.tar.gz"
      sha256 "db777e93aa431e3c53b4e2b96e6ec6820dae3645ecd0304c85b6d136e57bb6e0"
      define_method(:install) do
        bin.install "ccp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clnt/claude-code-profiles/releases/download/v0.1.1/ccp_0.1.1_linux_arm64.tar.gz"
      sha256 "08aa6470cd157539c85c358ea3886e991ffad02cf62d1e5e088fca68de8331c0"
      define_method(:install) do
        bin.install "ccp"
      end
    end
  end
end
