# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccp < Formula
  desc "Manage configuration profiles for Claude Code"
  homepage "https://github.com/clnt/claude-code-profiles"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clnt/claude-code-profiles/releases/download/v0.1.2/ccp_0.1.2_darwin_amd64.tar.gz"
      sha256 "069e72cdb3ed186c24c22f5f6c7c2c496b69a40a2d9f4bc9efaed34992ab85ff"

      define_method(:install) do
        bin.install "ccp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clnt/claude-code-profiles/releases/download/v0.1.2/ccp_0.1.2_darwin_arm64.tar.gz"
      sha256 "86bdefef603edc16de4d0e85a2f618010210c31210f55c8d472246b5d58ccf49"

      define_method(:install) do
        bin.install "ccp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/clnt/claude-code-profiles/releases/download/v0.1.2/ccp_0.1.2_linux_amd64.tar.gz"
      sha256 "c80419ea7f30e8aef74a2590170b28e6f9b7c26892711063e9eae3a0181dc992"
      define_method(:install) do
        bin.install "ccp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clnt/claude-code-profiles/releases/download/v0.1.2/ccp_0.1.2_linux_arm64.tar.gz"
      sha256 "ac326cda9e9a866e70beac97a6c99c05965d620ec847156a5e58962ce24e80c1"
      define_method(:install) do
        bin.install "ccp"
      end
    end
  end
end
